SELECT * FROM (
    SELECT ANIMAL_ID, i.NAME
            FROM ANIMAL_INS i JOIN ANIMAL_OUTS o
            USING (ANIMAL_ID)
            ORDER BY TO_NUMBER(TO_CHAR(o.DATETIME, 'YYYYMMDDHHmmSS')) - TO_NUMBER(TO_CHAR(i.DATETIME, 'YYYYMMDDHHmmSS')) DESC
) WHERE ROWNUM < 3
