-- 코드를 입력하세요
SELECT * FROM (
    SELECT i.NAME, i.DATETIME
    FROM ANIMAL_INS i
    LEFT JOIN ANIMAL_OUTS o
    USING (ANIMAL_ID)
    WHERE o.DATETIME IS NULL
    ORDER BY i.DATETIME
)
WHERE ROWNUM <= 3